language: python

python: "3.7"

services: postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database broker;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script: coverage run --source='broker/apps' manage.py test && coverage report

after_success: coveralls
